name: Deploy to EC2 on main push
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
          
      - name: Create deployment package
        run: |
          tar -czf deploy.tar.gz .next package.json package-lock.json next.config.js public node_modules
          
      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_LIVE_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deploy.tar.gz"
          target: "/home/ubuntu"
          
      - name: Extract and restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_LIVE_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/chefriend-frontend
            
            # 기존 파일 백업
            if [ -d ".next" ]; then
              mv .next .next.backup
            fi
            
            # 새 빌드 파일 압축 해제
            tar -xzf /home/ubuntu/deploy.tar.gz -C /home/ubuntu/chefriend-frontend
            rm /home/ubuntu/deploy.tar.gz
            
            # PM2 재시작
            if pm2 list | grep -q "chefriend"; then
              pm2 reload chefriend
            else
              pm2 start npm --name chefriend -- run start -- -p 3000
            fi
            pm2 save
            
            # 백업 삭제
            rm -rf .next.backup
